name: learn-github-actions
run-name: ${{ github.actor }} work with Github actions
on: [push]
jobs:
  lint-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run test
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci --legacy-peer-deps
      - run: npm run build
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run coverage
      - uses: actions/upload-artifact@v3
        name: Archive coverage report
        with:
          name: coverage-report
          path: coverage
